language: ruby
rvm:
  - 2.5.0
  - jruby

install:
  - bundle install

services:
  - postgresql

script:
  - bin/rails db:create
  - bin/rails db:migrate
  - bundle exec rspec spec
  - bundle exec rubocop