language: ruby

rvm:
  - 2.5.0

cache: bundler

addons:
  code_climate:
    repo_token: 89507b1366b6f2f26ae8bc3c023cc5a472a89f206980b77982f88f1abb1302b0

install:
  - bundle install

services:
  - postgresql

script:
  - bin/rails db:create
  - bin/rails db:migrate
  - bin/rails db:seed
  - bundle exec rspec spec

after_success:
  - bundle exec codeclimate-test-reporter
